AssignmentTest/AssignmentTest/Models/Product.cs
using AssignmentTest.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AssignmentTest.Models
{
    
    public class Product
    {
        //ID
        public int ID { get; set; }

        //CateID
        [DisplayName("Category Name")]
        public int CateID { get; set; }

        //Product Name
        [Required]
        [StringLength(100, MinimumLength = 2)]
        [DisplayName("Product Name")]
        public string ProductName { get; set; }

        //Price
        [Required]
        public double Price { get; set; }

        public int Quantity { get; set; }


        [ForeignKey("CateID")]
        public virtual Category Category { get; set; }

        public Product()
        {
                
        }

        public Product(ProductViewModel pv)
        {
            this.ID = pv.ID;
            this.ProductName = pv.ProductName;
            this.Price = pv.Price;
        }
    }
}

AssignmentTest/AssignmentTest/Models/ViewModel/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AssignmentTest.Models.ViewModel
{
    public class ProductViewModel
    {
        //ID
        [DisplayName("Product ID")]
        public int ID { get; set; }

        //Product Name
        [DisplayName("Product Name")]
        [Required(ErrorMessage = "Please enter Product name !")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Length must be at least 2 characters and maximum 100 characters !")]
        public string ProductName { get; set; }

        //Price
        [DisplayName("Product ID")]
        [Required(ErrorMessage = "Please enter Price !")]
        public double Price { get; set; }


        public ProductViewModel()
        {

        }

        public ProductViewModel(Product pv)
        {
            this.ID = pv.ID;
            this.ProductName = pv.ProductName;
            this.Price = pv.Price;
        }
    }
}

AssignmentTest/AssignmentTest/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssignmentTest.Data;
using AssignmentTest.Models;
using PagedList;

namespace AssignmentTest.Controllers
{
    public class ProductsController : Controller
    {
        private ShopContext db = new ShopContext();

        // GET: Products
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder; //PageList
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CategorySortParm = String.IsNullOrEmpty(sortOrder) ? "cate_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            //PageList
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var products = db.Products.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ProductName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(s => s.ProductName);
                    break;
                case "cate_desc":
                    products = products.OrderByDescending(s => s.Category.CategoryName);
                    break;
                case "Price":
                    products = products.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(s => s.Price);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductName);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult IndexAjax(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder; //PageList
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            //PageList
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var products = db.Products.AsQueryable();
           
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ProductName.Contains(searchString)
                    || s.Category.CategoryName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(s => s.ProductName);
                    break;
                case "Price":
                    products = products.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(s => s.Price);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductName);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return PartialView(products.ToPagedList(pageNumber, pageSize));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CateID = new SelectList(db.Categories, "ID", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CateID,ProductName,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CateID = new SelectList(db.Categories, "ID", "CategoryName", product.CateID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CateID = new SelectList(db.Categories, "ID", "CategoryName", product.CateID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CateID,ProductName,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CateID = new SelectList(db.Categories, "ID", "CategoryName", product.CateID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssignmentTest/AssignmentTest/Controllers/ShoppingCartController.cs
using AssignmentTest.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using AssignmentTest.Models;

namespace AssignmentTest.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        private ShopContext db = new ShopContext();
        public ActionResult Index()
        {
            return View((List<CartItem>)Session["giohang"]);
        }

        public ActionResult AddToCart(int id, int quantity)
        {
            Product product = db.Products.Find(id);

            if (quantity <= product.Quantity)
            {
                if (Session["giohang"] == null)
                {
                    Session["giohang"] = new List<CartItem>();

                }
                List<CartItem> giohang = Session["giohang"] as List<CartItem>;
                if (giohang.FirstOrDefault(m => m.proID == id) == null)
                {


                    CartItem cartItem = new CartItem()
                    {
                        proID = product.ID,
                        ProName = product.ProductName,
                        Price = product.Price,
                        Quantity = quantity,

                    };


                    giohang.Add(cartItem);
                    Debug.WriteLine(giohang.Count());

                }
                else
                {
                    CartItem cartItem = giohang.FirstOrDefault(m => m.proID == id);
                    cartItem.Quantity += quantity;
                }


                return Json(new
                {
                    code = 200,
                    message = "success",
                    JsonRequestBehavior.AllowGet
                });
            }
            else
            {
                return Json(new
                {
                    error = "Error msg",
                    JsonRequestBehavior.AllowGet

                });
            }
        }

        public ActionResult UpdateCart(int id, int quantity)
        {

            Debug.WriteLine(id);
            Debug.WriteLine(quantity);


            Product product = db.Products.Find(id);
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem cartItem = giohang.FirstOrDefault(m => m.proID == id);

            if (quantity <= product.Quantity)
            {
                if (cartItem != null)
                {
                    cartItem.Quantity = quantity;

                    return Json(new
                    {
                        code = 200,
                        message = "success",
                        JsonRequestBehavior.AllowGet
                    });
                }
                else
                {
                    return Json(new
                    {
                        code = 400,
                        error = "Error msg",
                        JsonRequestBehavior.AllowGet
                    });
                }
            }
            else
            {
                return Json(new
                {

                    error = "Error msg",
                    JsonRequestBehavior.AllowGet
                });
            }



        }

        public ActionResult Remove(int Id)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            giohang.RemoveAll(x => x.proID == Id);

            return Json(new
            {

                message = "success",
                JsonRequestBehavior.AllowGet
            });
        }

    }
}

AssignmentTest/AssignmentTest/Views/Products/Create.cshtml
@model AssignmentTest.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CateID, "CateID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CateID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AssignmentTest/AssignmentTest/Views/Products/Delete.cshtml
@model AssignmentTest.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssignmentTest/AssignmentTest/Views/Products/Details.cshtml
@model AssignmentTest.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AssignmentTest/AssignmentTest/Views/Products/Edit.cshtml
@model AssignmentTest.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CateID, "CateID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CateID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AssignmentTest/AssignmentTest/Views/Products/Index.cshtml
@model PagedList.IPagedList<AssignmentTest.Models.Product>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Ajax.BeginForm("IndexAjax", "Products", new AjaxOptions()
{
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    OnFailure = "failedID",
    LoadingElementId = "loadingId",
    UpdateTargetId = "resultId",
}))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="hidden" name="sortOrder" value="@Request.QueryString["sortOrder"]" />

        <input type="submit" value="Search" id="btn-submit" />
    </p>
}
<img id="ajax-loader" width="50" src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AAjax_loader_metal_512.gif&psig=AOvVaw0qO-PDXotvB_T3NmxcX2g7&ust=1646274259315000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNjL7NmvpvYCFQAAAAAdAAAAABAJ" style="display:none" />


<div id="resultId">
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Category Name", "Index", new { sortOrder = ViewBag.CategorySortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>

<!-- Ajax Page-->
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            $("input[name=SearchString]").on("keyup change", function (e) {
                $("#btn-submit").click();
            })


        })
    </script>
    <script>
        $(function () {
            $("#addToCart").click(function () {
                var model = {};
                model.Id = $('#productid').val();
                model.quantity = $('#quantity').val();
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AddToCart", "ShoppingCart")",
                    data: JSON.stringify(model),
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.code == 200) {
                            alert("Thêm giỏ hàng thành công!")
                        }
                    },
                    error: function (data) {
                    }
                })
            })
        })
    </script>
}

AssignmentTest/AssignmentTest/Views/Products/IndexAjax.cshtml
@model PagedList.IPagedList<AssignmentTest.Models.Product>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div id="resultId">
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Category Name", "Index", new { sortOrder = ViewBag.CategorySortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>